### ISSUE TITLE
Install dependencies quietly

### ISSUE THREAD

**Issue by dirn** [tkukushkin/tox-poetry#10]
tox-poetry removes a lot of boilerplate from my [tox] configuration. The one thing that I miss about invoking [Poetry] in each environment, however, is the ability to use `--quiet` when running `poetry install`. The output from this command can be rather verbose, making it really cumbersome to find test errors from any environment other than the last one run.

I'm happy to submit a PR to change

    cmd.append("install")

to

    cmd.extend(["--quiet", "install"])  # or using += if that's the preferred style of the project

I realize, though, that some folks may want to see this output and so perhaps this behavior should be configurable. I've never worked on a [tox] plugin before so I'm not sure of the best way to go about doing that, but I can look into it if that's the approach you'd prefer.

[poetry]: https://python-poetry.org
[tox]: https://tox.readthedocs.io

**Comment by tkukushkin** [comment]
tox has `-v` option:
```
  -v, --verbose                    increase verbosity of reporting output.-vv mode turns off output redirection for package installation, above level two verbosity flags are passed through
                                   to pip (with two less level) (default: 0)
```

Maybe we should remove `--quiet` option if tox started with 2 or more verbose level?

**Comment by dirn** [comment]
I didn't know about the `-vv` behavior with pip. Seems like a good idea to mimic that with Poetry. I'll take a look at that later today.

**Comment by tkukushkin** [comment]
I looked more closely on the output of tox and saw that poetry output is not shown.

If you are referring to the line starting with `py39 installed: ...`, then the reason of so verbose output is the fact that poetry does not install packages by their names, but chooses the right distribution and installs a specific "file" directly (platform wheel for example). tox shows all installed packages with full path to installed files in this case. Plugin can't control this behavior.

**Comment by dirn** [comment]
Oh you're right. I thought the difference was the `--quiet` flag. The difference is actually that I'm using the global Poetry which installs everything outside of the tox environment, thus resulting in nothing to show as installed. That's a shame but it's good to better understand what's going on. Thanks.
