### ISSUE TITLE
`tox` vs `python -m tox`

### ISSUE THREAD

**Issue by sebastian-philipp** [tkukushkin/tox-poetry#11]
I tried to make use of tox-poetry, but wasn't really able to make it work with the `tox` binary. If tox is installed within a venv, somehow tox still tries /usr/bin/python3 to set up the build environment:

```
$ which tox                  
~/Repos/testrepo/venv/bin/tox
$ tox --verbose -r -e py3
using tox.ini: /home/sebastian/Repos/testrepo/tox.ini (pid 2800758)
using tox-3.25.0 from /home/sebastian/.local/lib/python3.10/site-packages/tox/__init__.py (pid 2800758)
py3 cannot reuse: -r flag
py3 recreate: /home/sebastian/Repos/testrepo/.tox/py3
[2800765] /home/sebastian/Repos/testrepo/.tox$ /usr/bin/python3 -m virtualenv --no-download --python /usr/bin/python3 py3 >py3/log/py3-0.log
write config to /home/sebastian/Repos/testrepo/.tox/py3/.tox-config1 as '8604d1eca368d54325c0125e521cf211b653ad74a277821325ab35c97346c314 /usr/bin/python3\n3.25.0 0 0 0'
[2800773] /home/sebastian/Repos/testrepo$ /home/sebastian/Repos/testrepo/.tox/py3/bin/python -m pip freeze >.tox/py3/log/py3-1.log
py3 installed: 
py3 run-test-pre: PYTHONHASHSEED='2244003987'
```
versus:
```
$ which python
~/Repos/testrepo/venv/bin/python
$ python -m tox --verbose -r py3 -e py3
using tox.ini: /home/sebastian/Repos/testrepo/tox.ini (pid 2800940)
using tox-3.25.0 from /home/sebastian/Repos/testrepo/venv/lib64/python3.10/site-packages/tox/__init__.py (pid 2800940)
py3 cannot reuse: -r flag
py3 recreate: /home/sebastian/Repos/testrepo/.tox/py3
[2800947] /home/sebastian/Repos/testrepo/.tox$ /home/sebastian/Repos/testrepo/venv/bin/python -m virtualenv --no-download --python /home/sebastian/Repos/testrepo/venv/bin/python py3 >py3/log/py3-0.log
py3 installdeps: /home/sebastian/Repos/testrepo/venv/bin/poetry install
[2800954] /home/sebastian/Repos/testrepo$ /home/sebastian/Repos/testrepo/venv/bin/poetry install >.tox/py3/log/py3-1.log
^CERROR: got KeyboardInterrupt signal
$ 
```

Maybe this is something to document somewhere?

**Comment by tkukushkin** [comment]
Hi! Can you check if the problem persists without using the tox-poetry plugin? This plugin does not create a virtual environment, it is done by tox itself, so I do not even know how I can help.

**Comment by sebastian-philipp** [comment]
> Hi! Can you check if the problem persists without using the tox-poetry plugin? This plugin does not create a virtual environment, it is done by tox itself, so I do not even know how I can help.

Yeah, I think the issue is that tox_poetry.py is not even considered in my case. I don't think this something you can solve in the code. Just something you might want to document.

**Comment by tkukushkin** [comment]
It just seems that the problem is specific to your environment, me and the developers in the company where I work have not had such problems, we all use tox directly, not through `tox -m`.
