### ISSUE TITLE
where all the artifacts be installed into?

### ISSUE THREAD

**Issue by zillionare** [tkukushkin/tox-poetry#12]
I need run doctest against all *.py files, this is how:

```
#tox.ini
commands =
    /bin/sh -c 'for file in `find omicron -name *.py`;do {envpython} -m doctest $file;done'
```
however, all the deps are not installed into {envpython}'s path so the command fails.

Would you please inform me where are these deps installed into?

**Comment by tkukushkin** [comment]
Hello, @zillionare! I cannot reproduce your problem.

My tox.ini:
```ini
[tox]
envlist = py310

[testenv]
commands =
  /bin/sh -c '{envpython} -m pip freeze'
```
In tox output I see that all deps installed. Are you shure, that your tox uses tox-poetry plugin? Can you show your full tox output?

**Comment by zillionare** [comment]
thanks for take care of this case. Finally I move on without tox-poetry. For others may get help from my experience, this is what finally I did:

```
    poetry run pytest --doctest-modules omicron
```
i.e, I'm using pytest's doctest now.
