### ISSUE TITLE
Does this support dev dependencies?

### ISSUE THREAD

**Issue by jrabbit** [tkukushkin/tox-poetry#3]
They don't seem to be installed. What about extras?

**Comment by tkukushkin** [comment]
Dev dependencies supported and installing (command is `poetry install`, which installs dev-dependencies too).

Extras are not supported yet, I will try to implement config option in tox.ini with list of extras to install.

**Comment by tkukushkin** [comment]
I added `extras` support in latest releases, can you check?

**Comment by jrabbit** [comment]
thanks I'll check
